#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored


def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets Twitter_screen_name")
    
    screen_name = sys.argv[1]
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # queries Twitter’s API for a user’s most recent 50 tweets
    tweets = helpers.get_user_timeline(screen_name, 50)
    if tweets is None:
        sys.exit("Someting went wrong :( \nMaybe the name provided does not exist, or the account is private.")
    
    # iterate trough the tweets, analyzing each one
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))
    
if __name__ == "__main__":
    main()
